In [1]:
import numpy as np

# Basics

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
b = np.array([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0]
])

In [6]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

# Get array dimension

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int64')

# Access/Change rows/columns in an Array

In [12]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

In [13]:
a.shape

(2, 7)

In [14]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
# Get specific element using row,column 
a[0][2]

3

In [16]:
a[1][4]

12

## Access all data from specific row 

In [17]:
a[1][:]

array([ 8,  9, 10, 11, 12, 13, 14])

## Access all data from a specific column 

In [23]:
a[:,4]

array([ 5, 12])

# Initializing an Array

In [24]:
my_array = np.full((3,3),23) # providing ((rows,columns), value)

In [25]:
my_array

array([[23, 23, 23],
       [23, 23, 23],
       [23, 23, 23]])

## copying from the shape of another array 

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
shape_np = np.full_like(a, 100)

In [28]:
shape_np

array([[100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100]])

## An array of random decimal values 

In [33]:
random_array = np.random.rand(3,4)

In [34]:
random_array

array([[0.64149816, 0.51732671, 0.49692221, 0.42178613],
       [0.90361465, 0.12617129, 0.4203782 , 0.04562469],
       [0.82019958, 0.53521211, 0.35563432, 0.93229172]])

## An array of random integer values

In [39]:
random_int = np.random.randint(1,11, size = (2,5))

In [40]:
random_int

array([[ 5,  4,  1,  7,  7],
       [ 9, 10,  7,  9, 10]])

# Vertically stack vectors

In [42]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
stacked = np.vstack([v1,v2,v1])
stacked

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])